// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY3pn2Z66PakP9Fb4EHWoGToyfwn1WyKE',
    appId: '1:47960191539:web:8ad928332cfdc80484a946',
    messagingSenderId: '47960191539',
    projectId: 'flutterfire-selvia-g211200080',
    authDomain: 'flutterfire-selvia-g211200080.firebaseapp.com',
    storageBucket: 'flutterfire-selvia-g211200080.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw9q6W_NcWtObwZm4TY0NG5O_ra6d7y_s',
    appId: '1:47960191539:android:290252264f90dad584a946',
    messagingSenderId: '47960191539',
    projectId: 'flutterfire-selvia-g211200080',
    storageBucket: 'flutterfire-selvia-g211200080.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbgEjJ8qbb6qIIZFE2DXtWp4nywpAFkFs',
    appId: '1:47960191539:ios:addb37087431950f84a946',
    messagingSenderId: '47960191539',
    projectId: 'flutterfire-selvia-g211200080',
    storageBucket: 'flutterfire-selvia-g211200080.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbgEjJ8qbb6qIIZFE2DXtWp4nywpAFkFs',
    appId: '1:47960191539:ios:6420957c2352e0c584a946',
    messagingSenderId: '47960191539',
    projectId: 'flutterfire-selvia-g211200080',
    storageBucket: 'flutterfire-selvia-g211200080.appspot.com',
    iosBundleId: 'com.example.flutterlist.RunnerTests',
  );
}
